from __future__ import annotations

HEARTBEAT_SCHEMA_VERSION = 1
SERVICE_STATUS_SCHEMA_VERSION = 1
SERVICE_STATE_SCHEMA_VERSION = 1
PREFLIGHT_SCHEMA_VERSION = 1

EXPECTED_SDK_VERSION = "1.0.8"
EXPECTED_RUNTIME_VERSION = "1.0.73"
LATEST_MIGRATION_VERSION = 9

HEARTBEAT_WRITE_INTERVAL_SECONDS = 30.0
HEARTBEAT_STALE_SECONDS = 120.0
GATEWAY_DOWN_RESTART_SECONDS = 600.0
WATCHDOG_INTERVAL_SECONDS = 300
RESUME_SUPPRESSION_SECONDS = 60.0
RESTART_STORM_WINDOW_SECONDS = 900.0
RESTART_STORM_LIMIT = 3
SETUP_HEARTBEAT_TIMEOUT_SECONDS = 45.0
FORCE_RESTART_DRAIN_SECONDS = 15.0
